spring.application.name=statistic_service
server.port=8085

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/statistic_db

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true
spring.rabbitmq.listener.direct.observation-enabled=true

management.tracing.sampling.probability=1.0
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-no-trace},spanId=%X{spanId:-no-span}]

tracking.rabbit.exchange=tracking.events
tracking.rabbit.queue.impression=statistics.impression.queue
tracking.rabbit.queue.click=statistics.click.queue
tracking.rabbit.queue.order=statistics.order.queue
tracking.rabbit.routing.impression=tracking.impression
tracking.rabbit.routing.click=tracking.click
tracking.rabbit.routing.order=tracking.order

# Seed demo statistics data when collection is empty
app.statistics.seed.enabled=false

# Logging
logging.level.com.example.statistic_service=INFO


spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){orange} [%clr(%thread){blue}] %clr(%-5level) %clr(%logger{36}){cyan} - %msg%n

