spring.application.name=recommend_service
server.port=8086

recommend.product.base-url=http://localhost:8086
recommend.tracking.impression-url=http://localhost:8095/tracking/events/impression
recommend.seed.candidate-product-ids=1,2,3,4,5,6,7,8
recommend.seed.display-count=3

spring.output.ansi.enabled=ALWAYS

spring.data.redis.host=localhost
spring.data.redis.port=6379
