spring.application.name=recommend-service
server.port=8096

# MongoDB
spring.data.mongodb.uri=mongodb://localhost:27017/recommend_db

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# URL của core_business service (gọi để lấy product theo category)
core.service.url=http://localhost:8087

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Logging
logging.level.com.example.recommend_service=DEBUG
spring.output.ansi.enabled=ALWAYS
